number1=int(input("숫자1: "))
number2=int(input("숫자2: "))
print("--------------")
print(number1,"과",number2,"의 합은",number1+number2,"입니다.")
print(number1,"과",number2,"의 곱은",number1*number2,"입니다.")
print(number1,"과",number2,"의 뺄셈은",number1-number2,"입니다.")
print(number1,"과",number2,"의 나눗셈은",number1/number2,"입니다.")
print(number1,"과",number2,"의 나머지는",number1%number2,"입니다.")